### PR TITLE
Finish making website responsive

### PR DESCRIPTION
**Pull request by chensokheng123**
what do you think? you can check this link https://hololen.netlify.com/.

### CODE REVIEW

**Comment by IshanManchanda** [comment]
Pretty good, I really like some of the elements. You've managed to retain most of the desktop design on mobile while is pretty cool.

I'll give it a closer inspection a little later, but as of now, here are some things I found worth looking at:

1. The social icons in the footer can be made a tad bit smaller and a little bit of space can be added between them.

2. The MS logo in the navbar can also be made slightly smaller.

3. On the main page, the text in the cards is too close to the edge - add some padding there.

4.  Spacing between cards on the second page is uneven - this is by design on desktop but it doesn't look good on mobile.

See what you can do with these, I'll test it out on desktop later today and merge. :)

**Comment by IshanManchanda** [comment]
Also, have a look at #2. I'm considering moving to bootstrap. Once that's done, making the cards responsive would be a piece of cake.

**Comment by chensokheng123** [comment]
Thank you. I am working on it and I will show you the result.

**Comment by chensokheng123** [comment]
New update.

-  The social icons in the footer are smaller and have more space.
-  The MS logo is smaller
- On the main page, the text in the cards has some padding now
- The spacing between cards on the second page is okay now- 

What do you think about the new update?
lets me know if there is something you want to be changed. Thank you.

**Comment by IshanManchanda** [comment]
Good job! Seems pretty good, so I'm merging.

I unfortunately didn't get time to test it out on desktop. If anything needs to be changed, I'll create a new issue.

**Pull request merged**
